### ISSUE TITLE
Milestone 3 to do

### ISSUE THREAD

**Issue by SamEdwardes** [UBC-MDS/DSCI_532_L01_group101_dashboards#37]
- [ ] **maintenance of python app**
    - see priority list, not all changes need to be made
    - document what we have done in the reflect, also document what else should be done
    - suggested changes:
        - [x] #35 (@agdal1125 working on this)
        - [ ] #39 suggestions from Ellen:
            - [x] `For the line plots, there is a default showing for developing countries but not for developed countries, which is confusing when you first open up the app because the developing countries are plotted, but "developed countries" is selected. This should be fixed (High priority).` (@agdal1125)
            - [x] `The app description is good, but you could clarify that the values listed at the top are the mean for the entire world. You should also clarify the purpose of “GDP log” in the World Map graph` (@zoepan00 to update the README to clarify this)
            - [ ] `The user needs to use a scroll bar to see the entire graph, which is inconvenient.`
            - [ ] `For the “point colour” part in the scatterplot, it would be interesting to have the option to only show developed vs. undeveloped countries rather than both at the same time (lower priority).`
    - suggestions from peers (#44):
        - [x] increasing text size (@agdal1125)
        - [ ] correcting cut off (@agdal1125)
        - [x] moving position of control buttons (@agdal1125)
        - [x] fixing the summary stats order (@agdal1125)
- [x] **reflection** (@SamEdwardes)
    - lives on GitHub.com
    - link to GitHub issues where appropriate
- [x] **update readme from python app** (@zoepan00)
    - `You will be recreating your app using DashR. Now that your app is approaching its final state, you should update your README, proposal, and app sketch to match what your app will actually be doing and showing. As a rough guideline of effort, you should spend no more than 1-2 hours in total for this section. To help your TAs grading your work, instead of submitting a link to your file directly, you should submit a link that compares two commits of your proposal. We will show you how to do this in the lab session, but here is a guide to do this.`
- [x] **staring project 2 (R app)** (@zoepan00) 
    - create a new repo on GitHub.com under the MDS organization (each of team member should then fork this repo
    - create plots in ggplot (lets use notebooks like we did before?) (remember to make sure plots are in functions, and also that any data wrangling required is in a function)
        - [x] line plots (@SamEdwardes )
        - [ ] heat map (@agdal1125) 
        - [ ] scatter plot (@zoepan00)
    - add screenshot of plot progress in ggplots

**Comment by zoepan00** [comment]
I created project2 repo https://github.com/UBC-MDS/DSCI_532_L01_group101_project2, please have a look and fork

**Comment by SamEdwardes** [comment]
Thank you @zoepan00  - can you add Jake and I as contributors if you have not already?

**Comment by zoepan00** [comment]
Yes I did

**Comment by SamEdwardes** [comment]
See issue #44 where I have updated the summary of the feedback. I will also include this in a future PR to update the reflection document.

**Comment by SamEdwardes** [comment]
Finished the reflection document (#47). I think the only remaining items are:
- Start to create map plot using R (@Jake)
- Add screenshots of in progress R plots to README of R dashboard repo (@Zhengyang(Zoe) Pan)
- Review pull requests for each dashboard to ensure we don’t miss anything! (Everyone)
